#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
osascript - "$DIR/tofa" <<'APPLESCRIPT'
on run argv
  tell application "Terminal"
    activate
    do script (item 1 of argv)
  end tell
end run
APPLESCRIPT
